base_url = "https://georgiabains.com"
title = "Georgia Bains"
description = "TODO: Meta description"
default_language = "en"
compile_sass = false
minify_html = true
author = "Georgia Bains"
build_search_index = true
generate_sitemap = true
generate_robots_txt = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "nord"
smart_punctuation = true

[extra]
# Put all your custom variables here
