base_url = "https://georgiabains.com"
title = "Georgia Bains"
description = "TODO: Meta description"

default_language = "en"
author = "Georgia Bains"

compile_sass = false
minify_html = true

taxonomies = [
  { name = "tagged", feed = true, paginate_by = 5 }
]

build_search_index = true
generate_sitemap = true
generate_robots_txt = true

[markdown]
highlight_code = true
# Passes WCAG 2.1 AA accessibility requirements
highlight_theme = "boron"
smart_punctuation = true

[extra]
# Put all your custom variables here
